name: Remove old package versions
on:
  workflow_dispatch:
jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: purge packages
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: headscale-webui
          token: ${{ secrets.GITHUB_TOKEN }}
